spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true
  properties:
    hibernate.format_sql: true
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  session:
    store-type: jdbc
#springdoc:
#  version: '@project.version@'
#  api-docs:
#    path: /api-docs
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  swagger-ui:
#    operations-sorter: alpha
#    tags-sorter: alpha
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true
#    doc-expansion: none
#  paths-to-match:
#    - /api/**
server.servlet.encoding.force-response: true